#!/bin/bash
#
#kolmnurk vasakult paremale
#
for ((r=1; r<6; r++))
do 
   # trükime reanumbri ilma reavahetuseta
	echo -n "$r"
	for ((v=1; v<$((6-$r+1)); v++))
	do
	echo -n "*"
	done
   # kui rida lõppeb - reavahetus
	echo
done
