#!/bin/bash
#
#kell mis näitab aega
echo "Sisesta kellaaeg "
	read i
	if [ $i -lt 6 ];then
	echo "Head ööd!"

	elif [ $i -lt 12 ];then
	echo "Here hommikust!"

	elif [ $i -lt 19 ];then
	echo "Tere päevast!"

	elif [ $i -lt 23 ];then
	echo "Tere õhtust"

	elif [ $i -lt 25 ];then
	echo "Head ööd"

else
echo "Vale arv"
fi
