#!/bin/bash
#
# arvu positiivsuse/negatiivsuse kontroll
#
#küsime väärtused kasutaja käest
echo -n "sisesta arv: "
read arv
# kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]; then
   echo "$arv on positiivne"
#juhul kui väärtus on negatiivne
#siis arv peab olema väiksem kui 0
elif [ $arv -lt 0 ]; then
   echo "$arv on negatiivne"
#kui esimene tingimus
#või teine tingimus ei sobinund
#siis kasuta else osa
else
   echo "$arv on neutraalne"
#if lause tuleb korralikult lõpetada
fi
